Repository DomLucaz/Project-Quiz-Squad2, pull requests merged in 2023-07, with the labels that each got.

#2 Add base project
  index.html
  script/script.js
  style/style.css
Labels: enhancement

#22 Refactor: atualização do html e estilização com CSS
  index.html
  style/style.css
Labels: enhancement

#23 Update Readme
  README.md
Labels: documentation

#25 style:inicio da implementação da função darkmode
  index.html
  script/script.js
  style/style.css
Labels: enhancement

#27 Style: atualização html e css incluso com a função dark-light
  index.html
  style/style.css
Labels: bug, enhancement

#30 feat - Implementando a funcionalidade cronômetro
  index.html
  script/cronometro.js
Labels: enhancement

#31 bug - velocidade do cronometro ao reiniciar
  script/cronometro.js
Labels: bug

#41 Função concluir (armazena pontuação, valida questões)
  script/cronometro.js
  script/informacoes.js
  script/script.js
  script/temaJS.js
Labels: enhancement

#43 implementação da estilização do modo dark e algumas modificações nos …
  index.html
  style/style.css
Labels: enhancement

#44 Trilha sonora
  index.html
  script/cronometro.js
  script/script.js
  som/trilha2.mp3
Labels: enhancement

#46 bug do ícone de Audio
  index.html
Labels: bug

#48 style: criação de componentes da seção de resultado concluido e aprim…
  index.html
  style/style.css
Labels: enhancement

#49 atualizaçoes e correçoes nas estilização da página
  index.html
  script/script.js
  style/style.css
Labels: enhancement

#50 Adequação na validação, coloração das questões, botão continuar
  index.html
  script/script.js
  script/temaCSS.js
  script/temaHtml.js
Labels: enhancement

#52 Bug do required
  script/script.js
Labels: bug

#53 Popular a tabela resultados e correção de um bug do tempo na tabela …
  script/cronometro.js
  script/script.js
Labels: bug, enhancement

#55 Resolução de bug
  index.html
  script/populate.JS
  script/script.js
Labels: bug

#57 correção do bug da coloração
  script/script.js
Labels: bug

#58 Resolvendo bug html
  index.html
  script/script.js
Labels: bug

#61 feat - visibilidade do cronometro ao usuário
  index.html
  script/cronometro.js
  script/script.js
Labels: enhancement

#63 feat: função que zera campos do formulário.
  script/script.js
Labels: enhancement

#66 Audio - volume
  index.html
  script/script.js
  som/AlexGrohl - Monster.mp3
  som/trilha2.mp3
  som/trilhaSonora.mp3
Labels: enhancement

#68 Bug btn audio
  script/script.js
Labels: bug

#70 Resolução de bug
  script/script.js
Labels: bug

#71 elaboração média e ranking
  index.html
  script/script.js
Labels: enhancement
